# Generated by Django 3.2.7 on 2021-09-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('AlertId', models.AutoField(primary_key=True, serialize=False)),
                ('AlertStatus', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=500)),
                ('JWT', models.CharField(max_length=500)),
            ],
        ),
    ]
